//-----------   Categ

export const GET_CATEGORIES_REQUEST = "GET_CATEGORIES_REQUEST";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const ADD_NEW_CATEGORY_REQUEST = "ADD_NEW_CATEGORY_REQUEST";
export const ADD_NEW_CATEGORY_SUCCESS = "ADD_NEW_CATEGORY_SUCCESS";
export const ADD_NEW_CATEGORY_FAILURE = "ADD_NEW_CATEGORY_FAILURE";
//--------Current
export const GET_PRODUCTS_BY_SLUG = "GET_PRODUCTS_BY_SLUG";
export const GET_PRODUCT_PAGE_REQUEST = " GET_PRODUCT_PAGE_REQUEST ";
export const GET_PRODUCT_PAGE_SUCCESS = " GET_PRODUCT_PAGE_SUCCESS ";
export const GET_PRODUCT_PAGE_FAILURE = " GET_PRODUCT_PAGE_FAILURE ";

//********************* */

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_REQUEST = "LOGIN_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOAD_USER = "LOAD_USER";

/************** */

export const RESET_CART = "RESET_CART";

/************PROD details */

export const GET_PRODUCT_DETAILS_BY_ID_REQUEST =
  "GET_PRODUCT_DETAILS_BY_ID_REQUEST";
export const GET_PRODUCT_DETAILS_BY_ID_SUCCESS =
  "GET_PRODUCT_DETAILS_BY_ID_SUCCESS";
export const GET_PRODUCT_DETAILS_BY_ID_FAILURE =
  "GET_PRODUCT_DETAILS_BY_ID_FAILURE";

/********************CART */

export const ADD_TO_CART_REQUEST = "ADD_TO_CART_REQUEST";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILURE = "ADD_TO_CART_FAILURE";
